# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea4986c6f5c57a94c3185a5b908901337fca9d94d7eade86b1280c7f82d3701fce613cd7fbb0be49133b445715394e66bef6da8284c89539bb71a157b92bc95e

test:
  secret_key_base: 48e1de8d27d72e7e76840665f2d186732e533bbc9a6e808b1ea0c4676d7f2c6b4076c14fdd942c1fa22f2f8dfc1b4b59de723aa365562382de28980438d6a137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
